[package]
name = "otdr-fixer"
version = "0.1.0"
authors = ["James Harrison <james@talkunafraid.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
otdrs = "0.4.0"
clap = "3.0.0-beta.2"
walkdir = "2"